# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish npm package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "npm"
      - run: npm ci
      - run: npm test

      # Writes the version.json file and sets a tag on the version for prerelease builds.
      - name: Set package version
        run: node ./.github/workflows/setPackageVersion.js
        env:
          REF_NAME: ${{github.ref_name}}
          COMMIT_SHA: ${{github.sha}}
          IS_PRERELEASE: ${{ github.event.release.prerelease }}

      - run: npm run build

      # Publishes the package with a beta tag if this is a prerelease.
      - run: npm publish --access public --tag beta
        if: ${{ github.event.release.prerelease }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      # Publishes the package with the latest tag if this is not a prerelease.
      - run: npm publish --access public
        if: ${{ !github.event.release.prerelease }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
